substitutions:
  _REGION: asia-northeast1
  _SERVICE: kannri-web
  _API_URL: https://kannri-api-752144353294.asia-northeast1.run.app

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.frontend
      - --build-arg
      - PYTHON_API_BASE_URL=${_API_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kannri-app/${_SERVICE}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kannri-app/${_SERVICE}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kannri-app/${_SERVICE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kannri-app/${_SERVICE}:$COMMIT_SHA
